
[windows]
192.168.32.89:22



[windows:vars]

tempdir='C:\Windows\Temp'
ansible_connection=ssh
ansible_shell_type=powershell
win_admin=hello_admin
win_user=hello_user
win_admin_pass=salasana
win_user_pass=salasana
my_public_key=''
# winrm
#ansible_connection=winrm
# ansible_winrm_transport=ntlm


[all:vars]
ansible_python_interpreter=auto_silent
