---
# Linux base
- name: Base setup (Linux only)
  hosts: old:new
  become: true
  gather_facts: true
  vars_files:
    - vars/baseline.yml


# Create user 
- name: Create user on old systems
  hosts: old
  become: true
  vars_files:
    - vars/baseline.yml
  roles:
    - adduser


# Hardening new systems
- name: Hardening new systems
  hosts: new
  become: true
  vars_files:
    - vars/baseline.yml
  roles:
    - role: hardening
      vars:
        username: "{{ username }}"


# Windows
- name: Windows setup
  hosts: windows
  gather_facts: false
  vars_files:
    - vars/baseline.yml

  roles:
    - winuser
    - windows
