- name: Hello admin user
  ansible.windows.win_user:
    name: "{{win_admin}}"
    groups: Administrators
    groups_action: add
    password: "{{win_admin_pass}}"
    update_password: on_create
    state: present
  when: "'windows' in group_names"

- name: Hello admin profile
  ansible.windows.win_user_profile: 
    name: "{{win_admin}}"
    username: "{{win_admin}}"
    state: present
  when: "'windows' in group_names"
    
- name: Hello user
  ansible.windows.win_user:
    name: "{{win_user}}"
    groups: Users
    groups_action: add
    password: "{{win_user_pass}}"
    update_password: on_create
    state: present
  when: "'windows' in group_names"

- name: Hello user profile
  ansible.windows.win_user_profile: 
    name: "{{win_user}}"
    username: "{{win_user}}"
    username: "{{win_admin}}"
    state: present
  when: "'windows' in group_names"
 
